### ISSUE TITLE
Create issues from the message from Simone on 2022-07-15

### ISSUE THREAD

**Issue by hfu** [ggim-exercise/inventory#2]
- [x] Please view the attached most current download of data from both surveys. Seeking your assistance with adding the additional data received.  #3

- [x] Can we include the UN-GGIM Logo somewhere ? #4

- [x] Could we please include the following headings:
First heading:
"United Nations Global Geospatial Information Management (UN-GGIM) Working Group on Geospatial Information and Services for Disasters"
           Second heading:                                                                                                                                                                                                       "Global Disaster Risk Reduction (DRR) Organizations, Geospatial Information Services and Platforms Inventory Hub" #5

- [x] We may need to have a landing page first, with these logos and headings and introductory information and a key exists and then one clicks a link to access the hub. What do you think ?  #6

- [x] Properties for making public:
In looking back at both surveys, all the information captured would be useful to anyone. Nothing captured is sensitive information that would need to be made private.
Please make them all public and let's examine towards a final decision but doubt any would need to be private. #7

- [x] In agreement that we should include invitations to add more data, by providing the links to both surveys under the name of each.
Please include a section inviting Member States, disaster risk reduction and management organizations and relevant academia, private sector and United Nations system organizations to continue contributing to the global administration of the inventory surveys hub maintenance by completing the following surveys whenever new information becomes available. #8

A) UN-GGIM WG Disasters - DRR Organizations Inventory Survey: 
https://arcg.is/1jfGji2

B) UN-GGIM WG Disasters - DRR Geospatial Info & Services Platforms Inventory Survey:  
                 https://arcg.is/CKPOT

**Comment by hfu** [comment]
Successfully split into issues.
